### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by rycoshe** [PrimalZed/character-sheet-generator#14]
hi PrimalZed, i need a help with your character sheet generator, is there any way to contact you, by discord or something similar?

**Comment by PrimalZed** [comment]
What specific help do you need?

It's been a long time since I've done anything with this. If you need help on handlebars or scss, you can find online help for each of those. If you need help on the app itself, I understand GiGs on [Roll20's Character Sheets forum](https://app.roll20.net/forum/category/277980) has apparently continued to use it, and is preparing a tutorial. Frankly, they are going to be more familiar with using the app than me at this point.

**Comment by birdbrainiac** [comment]
That's a timely question. April is going to be the month of this tool on my site. I'll be writing a lot of in-depth articles, so keep an eye on this page: https://cybersphere.me/guide-to-sheet-templating/ - the handlebars-tool-specific articles will start appearing on the 2nd.

Since Zed is pointing you in my direction, I'm on the roll20 forum: https://app.roll20.net/users/157788/gigs. If you want to ask any questions, they might inform the content of future articles.

**Comment by birdbrainiac** [comment]
I'll delete this question in A little bit Zed - just letting you know I asked you a question on Roll20.
